// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujcsttptqvobkjkyorgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqY3N0dHB0cXZvYmtqa3lvcmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1Nzk2MzgsImV4cCI6MjA1MzE1NTYzOH0.EHqx_6OEkWqjTRU7vVbD8JXutfrCPxDGKmDsnEW-5Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);